#!/usr/bin/env python3
"""Generates the gateway's issuer registry from sites/registry.yaml.

Writes collector/registry.yaml, which is merged over collector/config.yaml by
passing both to the collector. The two files hold disjoint keys, so the merge is
a plain map union and never depends on how the confmap resolver treats lists.

Run with --check in CI to fail when the generated file is stale.
"""

import argparse
import os
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "sites", "registry.yaml")
COLLECTOR_OUT = os.path.join(ROOT, "collector", "registry.yaml")
SITE_ENV_OUT = os.path.join(ROOT, "sites", "generated", "site-env.txt")

HEADER = f"""# GENERATED by scripts/gen-registry.py from sites/registry.yaml. Do not edit.
#
# Merged over collector/config.yaml at startup, so the gateway trusts exactly
# the frontends the registry lists. `username_claim: iss` makes auth.subject the
# issuer URL, which a site cannot forge because the collector fetches that
# issuer's JWKS from the URL itself. transform/sitename then resolves the URL to
# a sitename centrally -- a `sitename` claim in the token is never trusted.
"""


def load():
    """Registry, with the unenrolled sites dropped."""
    with open(SOURCE, "r", encoding="utf-8") as fd:
        data = yaml.safe_load(fd)
    sites = [s for s in data["sites"] if s.get("issuer")]
    return data["audience"], sites


def duplicates(sites):
    """Issuers or sitenames claimed twice."""
    dupes = []
    for field in ("sitename", "issuer"):
        seen = set()
        for site in sites:
            if site[field] in seen:
                dupes.append(f"{field} {site[field]} appears more than once")
            seen.add(site[field])
    return dupes


def build(audience, sites):
    """Collector fragment for the registry."""
    providers = [{"issuer_url": s["issuer"], "audience": audience, "username_claim": "iss"} for s in sites]
    statements = [f'set(resource.attributes["sitename"], "{s["sitename"]}") ' f'where resource.attributes["sitename"] == "{s["issuer"]}"' for s in sites]
    return {
        "extensions": {"oidc": {"providers": providers}},
        "processors": {
            "transform/sitename": {
                # An unmapped issuer keeps its URL in `sitename` rather than
                # being dropped, so a half-finished enrollment is visible in
                # Grafana instead of silently unattributed.
                "error_mode": "ignore",
                "trace_statements": list(statements),
                "metric_statements": list(statements),
                "log_statements": list(statements),
            }
        },
    }


def siteEnv(audience, sites):
    """The block each frontend adds to /etc/environment."""
    lines = [
        "# GENERATED by scripts/gen-registry.py. One block per frontend.",
        "#",
        "# OIDC_ISSUER must stay byte-identical to the gateway's issuer_url: it is",
        "# what the frontend publishes as `issuer` in its discovery document, and",
        "# go-oidc compares the two exactly.",
        "",
    ]
    for site in sites:
        lines += [
            f"# {site['sitename']}",
            f"OIDC_ISSUER={site['issuer']}",
            f"OIDC_SITENAME={site['sitename']}",
            f"OIDC_EXTRA_AUDIENCE={audience}",
            f"OTLP_AUTH_URL={site['issuer']}",
            "OTLP_ENDPOINT=https://sense-otlp.nrp-nautilus.io",
            "",
        ]
    return "\n".join(lines)


def render(audience, sites):
    """Both generated artifacts, as text."""
    fragment = yaml.safe_dump(build(audience, sites), sort_keys=False, default_flow_style=False, width=10000)
    return HEADER + "\n" + fragment, siteEnv(audience, sites)


def main():
    """Generate, or verify that the checked-in copies are current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated files are stale")
    args = parser.parse_args()

    audience, sites = load()
    dupes = duplicates(sites)
    if dupes:
        for line in dupes:
            print(f"registry: {line}", file=sys.stderr)
        return 1

    collector, siteenv = render(audience, sites)
    stale = False
    for path, content in ((COLLECTOR_OUT, collector), (SITE_ENV_OUT, siteenv)):
        if args.check:
            current = open(path, "r", encoding="utf-8").read() if os.path.exists(path) else None
            if current != content:
                print(f"stale: {os.path.relpath(path, ROOT)}", file=sys.stderr)
                stale = True
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fd:
            fd.write(content)
        print(f"wrote {os.path.relpath(path, ROOT)}")

    if stale:
        print("run scripts/gen-registry.py", file=sys.stderr)
        return 1
    if not args.check:
        print(f"{len(sites)} issuers enrolled")
    return 0


if __name__ == "__main__":
    sys.exit(main())
