#!/usr/bin/env python3
"""Generates the gateway's issuer registry from sites/registry.yaml.

Writes collector/registry.yaml, which is merged over collector/config.yaml by
passing both to the collector, and collector/probes.yaml, the blackbox scrape
config. The two files hold disjoint keys, so the merge is a plain map union and
never depends on how the confmap resolver treats lists.

The two lists are NOT the same set. oidc providers come from the sites marked
enrolled; probe targets come from every site with a URL. An unreachable site
must stay probed -- that is how you learn it is unreachable -- but must not be
enrolled, because the oidc extension refuses to start if any single provider
fails and would take the whole fleet's ingest down with it.

Run with --check in CI to fail when the generated files are stale, and with
--verify to re-read each enrolled frontend's discovery document and confirm the
issuer still matches byte for byte.
"""

import argparse
import concurrent.futures
import json
import os
import ssl
import sys
import urllib.request

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "sites", "registry.yaml")
COLLECTOR_OUT = os.path.join(ROOT, "collector", "registry.yaml")
SITE_ENV_OUT = os.path.join(ROOT, "sites", "generated", "site-env.txt")
PROBES_OUT = os.path.join(ROOT, "collector", "probes.yaml")

HEADER = f"""# GENERATED by scripts/gen-registry.py from sites/registry.yaml. Do not edit.
#
# Merged over collector/config.yaml at startup, so the gateway trusts exactly
# the frontends the registry marks enrolled. `username_claim: iss` makes
# auth.subject the issuer URL, which a site cannot forge because the collector
# fetches that issuer's JWKS from the URL itself. transform/sitename then
# resolves the URL to a sitename centrally -- a `sitename` claim in the token is
# never trusted.
#
# Each issuer_url is byte-identical to what that frontend publishes in its
# discovery document; go-oidc compares them exactly and one mismatch stops the
# whole gateway. `scripts/gen-registry.py --verify` re-checks them against the
# live endpoints.
"""


def load():
    """Audience, the sites with a URL, and the subset that is enrolled.

    A site with no issuer URL is not known well enough to do either thing with.
    A site with a URL but `enrolled: false` is probed but not trusted.
    """
    with open(SOURCE, "r", encoding="utf-8") as fd:
        data = yaml.safe_load(fd)
    known = [s for s in data["sites"] if s.get("issuer")]
    enrolled = [s for s in known if s.get("enrolled", True)]
    return data["audience"], known, enrolled


def duplicates(sites):
    """Issuers or sitenames claimed twice."""
    dupes = []
    for field in ("sitename", "issuer"):
        seen = set()
        for site in sites:
            if site[field] in seen:
                dupes.append(f"{field} {site[field]} appears more than once")
            seen.add(site[field])
    return dupes


def build(audience, sites):
    """Collector fragment for the registry."""
    providers = [{"issuer_url": s["issuer"], "audience": audience, "username_claim": "iss"} for s in sites]
    statements = [f'set(resource.attributes["sitename"], "{s["sitename"]}") ' f'where resource.attributes["sitename"] == "{s["issuer"]}"' for s in sites]
    return {
        "extensions": {"oidc": {"providers": providers}},
        "processors": {
            "transform/sitename": {
                # An unmapped issuer keeps its URL in `sitename` rather than
                # being dropped, so a half-finished enrollment is visible in
                # Grafana instead of silently unattributed.
                "error_mode": "ignore",
                "trace_statements": list(statements),
                "metric_statements": list(statements),
                "log_statements": list(statements),
            }
        },
    }


PROBE_HEADER = """# GENERATED by scripts/gen-registry.py from sites/registry.yaml. Do not edit.
#
# Blackbox probing stays an OUTSIDE observer, deliberately. A site that has
# fallen over cannot push a metric saying it has fallen over, so probe_* and up
# cannot be push-native the way the rest of the fleet's metrics now are. These
# jobs are scraped here, in sense-viz, and remote-written into Mimir alongside
# the pushed series -- so the reachability and certificate-expiry panels keep
# working when the pull path from the sites retires.
#
# Every frontend with a known URL, from the same file the issuer registry comes
# from, so a site cannot be enrolled for OTLP and silently left unprobed. This
# list is deliberately WIDER than the enrolled set: a site the gateway cannot
# reach is exactly the one worth probing.
"""


def probes(sites):
    """Prometheus receiver config for the blackbox probes.

    Autogole ships a per-site *_MODEL_V4 job (authenticated https probe of the
    frontend) alongside the *_STATE scrape, and an *_ICMP_V4 job probing the
    host. Only the http half is reproduced: Gatekeeper on this cluster refuses
    NET_RAW, so the icmp prober cannot open a ping socket, and all three of the
    ported probe_* rules read the http probe anyway.

    sitename is stamped by a regex over `instance` for the same reason the
    gateway stamps it on the push path: the probe target cannot be trusted to
    name itself. Without it ProbeFailed (`probe_success == 0`) would fire with
    an empty sitename.

    The module is chosen per target rather than per job. `http_2xx` sets
    fail_if_not_ssl, so a plain-http issuer fails the probe even when the
    frontend answers 200 -- which is exactly what the four in-cluster MOHDEV
    frontends do, and they read as a four-site outage until the module matches
    the scheme. Splitting into two scrape jobs would have worked too, but it
    would also split the `job` label, and the ported probe_* alert rules match
    on it. Rewriting `__param_module` keeps one job.
    """
    return {
        "receivers": {"prometheus/probes": {"config": {"scrape_configs": [
            {
                "job_name": "siterm-probe-http",
                "scrape_interval": "60s",
                "metrics_path": "/probe",
                "params": {"module": ["http_2xx"]},
                "static_configs": [{"targets": [s["issuer"] for s in sites]}],
                "relabel_configs": [
                    {"source_labels": ["__address__"], "target_label": "__param_target"},
                    {"source_labels": ["__param_target"], "target_label": "instance"},
                    {"target_label": "__address__", "replacement": "blackbox:9115"},
                    {"source_labels": ["__param_target"], "regex": "http://.*", "target_label": "__param_module", "replacement": "http_2xx_plain"},
                ]
                + [
                    {"source_labels": ["instance"], "regex": s["issuer"], "target_label": "sitename", "replacement": s["sitename"]}
                    for s in sites
                ],
            }
        ]}}}
    }


def siteEnv(audience, sites):
    """The block each frontend adds to /etc/environment."""
    lines = [
        "# GENERATED by scripts/gen-registry.py. One block per frontend.",
        "#",
        "# OIDC_ISSUER must stay byte-identical to the gateway's issuer_url: it is",
        "# what the frontend publishes as `issuer` in its discovery document, and",
        "# go-oidc compares the two exactly.",
        "",
    ]
    for site in sites:
        lines += [
            f"# {site['sitename']}",
            f"OIDC_ISSUER={site['issuer']}",
            f"OIDC_SITENAME={site['sitename']}",
            f"OIDC_EXTRA_AUDIENCE={audience}",
            f"OTLP_AUTH_URL={site['issuer']}",
            "OTLP_ENDPOINT=https://sense-otlp.nrp-nautilus.io",
            "",
        ]
    return "\n".join(lines)


def render(audience, known, enrolled):
    """Every generated artifact, as text.

    oidc and the sitename map are built from `enrolled`; the probe targets from
    `known`, which also carries the sites the gateway cannot reach.
    """
    fragment = yaml.safe_dump(build(audience, enrolled), sort_keys=False, default_flow_style=False, width=10000)
    probeconf = yaml.safe_dump(probes(known), sort_keys=False, default_flow_style=False, width=10000)
    return HEADER + "\n" + fragment, siteEnv(audience, enrolled), PROBE_HEADER + "\n" + probeconf


def published(site, timeout=15):
    """The `issuer` a frontend actually advertises, or an error string.

    verify_mode is NONE deliberately: several frontends present site-issued
    certificates, and what is being checked here is the issuer string, not the
    chain. The gateway does verify the chain, which is a separate concern.
    """
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    url = site["issuer"].rstrip("/") + "/.well-known/openid-configuration"
    try:
        with urllib.request.urlopen(url, timeout=timeout, context=ctx) as response:
            return json.load(response).get("issuer"), None
    except Exception as ex:  # pylint: disable=broad-except
        return None, f"{type(ex).__name__}: {str(ex)[:70]}"


def verify(enrolled):
    """Check every enrolled issuer against its live discovery document.

    A mismatch here is what makes the gateway refuse to start -- go-oidc
    compares the two exactly -- and it is fatal for the whole collector, not
    just the offending site, so it is worth catching before a deploy.
    """
    problems = 0
    with concurrent.futures.ThreadPoolExecutor(max_workers=12) as pool:
        results = list(pool.map(published, enrolled))
    for site, (issuer, error) in zip(enrolled, results):
        if error is not None:
            print(f"UNREACHABLE {site['sitename']}: {error}", file=sys.stderr)
            print("            an enrolled issuer the gateway cannot reach stops it starting", file=sys.stderr)
            problems += 1
        elif issuer != site["issuer"]:
            print(f"MISMATCH    {site['sitename']}", file=sys.stderr)
            print(f"            registry:  {site['issuer']}", file=sys.stderr)
            print(f"            published: {issuer}", file=sys.stderr)
            problems += 1
    if problems:
        print(f"\n{problems} of {len(enrolled)} enrolled issuers would fail at gateway startup", file=sys.stderr)
        return 1
    print(f"{len(enrolled)} enrolled issuers match their discovery documents")
    return 0


def main():
    """Generate, or verify that the checked-in copies are current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated files are stale")
    parser.add_argument("--verify", action="store_true", help="re-read each enrolled frontend's discovery document")
    args = parser.parse_args()

    audience, known, enrolled = load()
    dupes = duplicates(known)
    if dupes:
        for line in dupes:
            print(f"registry: {line}", file=sys.stderr)
        return 1

    if args.verify:
        return verify(enrolled)

    collector, siteenv, probeconf = render(audience, known, enrolled)
    stale = False
    for path, content in ((COLLECTOR_OUT, collector), (SITE_ENV_OUT, siteenv), (PROBES_OUT, probeconf)):
        if args.check:
            current = open(path, "r", encoding="utf-8").read() if os.path.exists(path) else None
            if current != content:
                print(f"stale: {os.path.relpath(path, ROOT)}", file=sys.stderr)
                stale = True
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fd:
            fd.write(content)
        print(f"wrote {os.path.relpath(path, ROOT)}")

    if stale:
        print("run scripts/gen-registry.py", file=sys.stderr)
        return 1
    if not args.check:
        print(f"{len(enrolled)} issuers enrolled, {len(known)} probe targets")
    return 0


if __name__ == "__main__":
    sys.exit(main())
